version: '3.8'

services:
  postgredb:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - dbpostgre:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped  
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "p4ssw0rd"
    ports:
      - 8200:80
    depends_on:
      - postgredb
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  dbpostgre:
  pgadmin:

