version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: qwerty
      MARIADB_DATABASE: database
      MARIADB_USER: username
      MARIADB_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8000:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
    depends_on:
      - mariadb

volumes:
  mariadb-data:
