version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - '3306:3306'
    volumes:
      - mysqldb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8000:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysqldb
    depends_on:
      - mysqldb

volumes:
  mysqldb:
